
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_development
  username: postgres
  password: 'root'

test:
  <<: *default
  database: book_test
  username: postgres
  password: 'root'


production:
  <<: *default
  database: book_production
  username: postgres
  password: 'root'
